version: 2
jobs:
  build:
    docker:
        - image: karanchahal/go-protoc:1.0.0
    
    working_directory: /go/src/hydra-dht
    
    steps:  
      - checkout
      
      - restore_cache:
            keys:
              - v1-pkg-cache
      
      - run: 
          name: Building Project
          command: sh build.sh
      
      - run:
          name: Run unit tests and generate coverage report
          command: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Uploading test coverage report
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
